apiVersion: v1
kind: Service
metadata:
  name: auth-adapter
  namespace: istio-system
  labels:
    app: auth-adapter
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 40103
    targetPort: 40103
  selector:
    app: auth-adapter

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-adapter
  namespace: istio-system
  labels:
    app: auth-adapter
spec:
  replicas: 1 # change this as needed.
  template:
    metadata:
      labels:
        app: auth-adapter
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - name: auth-adapter
        image: sdrzlyz/istio-auth-adapter:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 40103
